function output = quadrotor_dynamics(phib,thetab,psib,wbx,wby,wbz,phim,thetam,w1,w2,w3,w4,dphim,dthetam)
%QUADROTOR_DYNAMICS
%    OUTPUT = QUADROTOR_DYNAMICS(PHIB,THETAB,PSIB,WBX,WBY,WBZ,PHIM,THETAM,W1,W2,W3,W4,DPHIM,DTHETAM)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    15-Apr-2023 20:23:09

t2 = cos(phib);
t3 = cos(phim);
t4 = cos(psib);
t5 = cos(thetab);
t6 = cos(thetam);
t7 = sin(phib);
t8 = sin(phim);
t9 = sin(psib);
t10 = sin(thetab);
t11 = sin(thetam);
t12 = t6.*5.0;
t13 = t11.*5.0;
t14 = t2.*t4;
t15 = t2.*t9;
t16 = t4.*t7;
t17 = t7.*t9;
t18 = t6.*9.6e+1;
t19 = t11.*9.6e+1;
t28 = (t3.*t10.*t11)./6.25e+4;
t29 = (t5.*t7.*t8)./6.25e+4;
t32 = (t2.*t3.*t5.*t6)./6.25e+4;
t33 = (t3.*t4.*t5.*t11)./6.25e+4;
t34 = (t3.*t5.*t9.*t11)./6.25e+4;
t41 = t8.*1.92e-4;
t42 = t3.*t6.*3.2e-4;
t43 = t8.*1.666666666666667e-5;
t44 = t3.*t6.*1.0e-5;
t20 = t10.*t17;
t21 = t10.*t14;
t22 = t10.*t15;
t23 = t10.*t16;
t35 = -t32;
t36 = -t34;
t24 = -t22;
t25 = -t23;
t26 = t14+t20;
t27 = t17+t21;
t45 = t28+t29+t35;
t30 = t15+t25;
t31 = t16+t24;
t37 = (t8.*t26)./6.25e+4;
t38 = (t3.*t6.*t27)./6.25e+4;
t39 = (t8.*t30)./6.25e+4;
t40 = (t3.*t6.*t31)./6.25e+4;
t46 = t33+t38+t39;
t47 = t36+t37+t40;
mt1 = [t46.*w1+t46.*w2+t46.*w3+t46.*w4;-t47.*w1-t47.*w2-t47.*w3-t47.*w4;-t45.*w1-t45.*w2-t45.*w3-t45.*w4-9.81e+2./1.0e+2];
mt2 = [wby.*wbz.*(-2.0./3.0)+t3.*w2.*(t13+t18).*3.333333333333333e-6-t3.*t11.*w1.*1.666666666666667e-5-t3.*t11.*w3.*1.666666666666667e-5+t3.*w4.*(t13-t18).*3.333333333333333e-6];
mt3 = [w3.*(t42+t43)-t8.*w2.*1.666666666666667e-5-t8.*w4.*1.666666666666667e-5+wbx.*wbz.*(2.0./3.0)-w1.*(t42-t43)];
mt4 = [-w1.*(t41+t44)+w3.*(t41-t44)+t3.*w4.*(t12+t19).*2.0e-6+t3.*w2.*(t12-t19).*2.0e-6];
output = [mt1;mt2;mt3;mt4];
